version: '3'
services:
  voice_synthesizer:
    image: dhruv961211/voices:tacotron2_hifigan
    network_mode: bridge
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    container_name: voice_synthesizer