# Use the NVIDIA CUDA runtime as a parent image
FROM nvidia/cuda:12.1.1-base-ubuntu20.04

# Set the working directory in the container
WORKDIR /app

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /app
COPY . /app

# # Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Run app.py when the container launches
 CMD ["flask", "run", "--host=0.0.0.0"]
# CMD ["tail", "-f", "/dev/null"]
